SELECT TOP 1000 [PRODUCTTYPE]
	  ,[CCUSERS]
	  ,[NUMCOPIESLIC]
	  ,[PRODUCTNAME]
	  ,[REGCOPIES]
	  ,[PILOTDATE]
	  ,[PRODUCTENABLED]
	  ,[INUSE]
  FROM [HSI].[PRODUCTSOLD] WHERE PRODUCTNAME = 'NAMED USER CLIENT'
  
  SELECT TOP 1000 [PRODUCTTYPE]
	  ,[CCUSERS]
	  ,[NUMCOPIESLIC]
	  ,[PRODUCTNAME]
	  ,[REGCOPIES]
	  ,[PILOTDATE]
	  ,[PRODUCTENABLED]
	  ,[INUSE]
  FROM [HSI].[PRODUCTSOLD] 
  WHERE PRODUCTNAME LIKE '%CLIENT%' AND REGCOPIES <> 0

SELECT RTRIM(UA.REALNAME) AS 'REAL NAME', RTRIM(UA.USERNAME) AS 'USERNAME', RTRIM(PS.PRODUCTNAME) AS 'LICENSE TYPE', RTRIM(RU.REGISTERNAME) AS 'WORKSTATION', UA.LASTLOGON, LU.HEARTBEAT, LU.CHECKIN
FROM HSI.LOGGEDUSER LU
INNER JOIN HSI.USERACCOUNT UA ON LU.USERNUM = UA.USERNUM
INNER JOIN HSI.PRODUCTSOLD PS ON LU.PRODUCTTYPE = PS.PRODUCTTYPE
INNER JOIN HSI.REGISTEREDUSERS RU ON LU.REGISTERNUM = RU.REGISTERNUM
ORDER BY UA.LASTLOGON DESC

SELECT * FROM USERXLICENSE USX
JOIN USERACCOUNT UAC
ON USX.USERNUM = UAC.USERNUM
 WHERE PRODUCTTYPE = 295
 ORDER BY LASTLOGON