-- SCRIPT : ONBASE_GetTransactionLogs.sql
-- LIST BATCH DETAILS ON A GIVEN TIMESTAMP RANGE
-- EASE ANALYTICS WITH EXCEL / PIVOT TABLES
-- FORMATED WITH : HTTPS://SQLFORMAT.ORG/
DECLARE @STARTDATE DATETIME = '2018-01-01 00:00:00'; -- START DATE RANGE
DECLARE @ENDDATE DATETIME = '2018-12-31 23:59:59'; -- END DATE RANGE

SELECT COUNT(*) AS TOTAL_TRNS  
FROM [hsi].[transactionxlog]
WHERE [hsi].[transactionxlog].logdate BETWEEN @STARTDATE AND @ENDDATE;

SELECT *
FROM [hsi].[transactionxlog]
WHERE [hsi].[transactionxlog].logdate BETWEEN @STARTDATE AND @ENDDATE
ORDER BY [hsi].[transactionxlog].logdate 

