/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [transactionnum]
      ,[tmessage]
      ,[action]
      ,[logdate]
      ,[num]
      ,[usernum]
      ,[itemnum]
      ,[docrevnum]
      ,[registernum]
      ,[actionnum]
      ,[subactionnum]
      ,[severityflag]
      ,[tracelvl]
      ,[extrainfo1]
      ,[extrainfo2]
  FROM [ONBASE_DEV].[hsi].[transactionxlog]