DECLARE @STARTDATE DATETIME = '2023-07-01 00:00:00'; -- START DATE RANGE
DECLARE @ENDDATE DATETIME = '2023-07-04 20:00:00'; -- END DATE RANGE
--DECLARE @JOB_NAME VARCHAR(120) = 'GL EXPORT - INITIATOR'; -- NAME OF THE BATCH PROCESS AS DEFINED IN IDIT
DECLARE @JOB_NAME VARCHAR(120) = 'SYS_GL_Export'; -- NAME OF THE BATCH PROCESS AS DEFINED IN IDIT


--STARTED > FAILED 
SELECT *  
FROM SH_BATCH_LOG AS SH
WHERE STATUS =4 
AND TRANSFER_TYPE != 13844
AND SH.START_TIME BETWEEN @STARTDATE AND @ENDDATE
AND GROUP_NAME LIKE  '%' + @JOB_NAME + '%';

--SCHEDULED > UNSCHEDULED
SELECT *  
FROM SH_BATCH_LOG AS SH
WHERE STATUS = 8 
AND TRANSFER_TYPE != 13844
AND SH.START_TIME BETWEEN @STARTDATE AND @ENDDATE
AND GROUP_NAME LIKE  '%' + @JOB_NAME + '%';

--PROCESSING > FAILED
SELECT *  FROM SH_BATCH_LOG AS SH
WHERE STATUS = 17 
AND TRANSFER_TYPE != 13844 
AND SH.START_TIME BETWEEN @STARTDATE AND @ENDDATE
AND GROUP_NAME LIKE  '%' + @JOB_NAME + '%';

-- RECURRING JOB SCHEDULED,RECURRING JOB PAUSED > RECURRING JOB UNSCHEDULED
SELECT *  
FROM  SH_BATCH_LOG AS SH  
WHERE STATUS IN (19,23) 
AND TRANSFER_TYPE != 13844
AND SH.START_TIME BETWEEN @STARTDATE AND @ENDDATE
AND GROUP_NAME LIKE  '%' + @JOB_NAME + '%';