-- GL EXPORT status and kill commands

-- Status retriever -----------------------------------------------------
-- Generic batch list for a given period of time
--SELECT * FROM SH_BATCH_LOG 
--WHERE CREATE_DATE BETWEEN '2023-07-02 08:00:00' AND '2023-07-02 23:59:59'
--AND GROUP_NAME LIKE '%GL EXPORT%';
DECLARE @STARTDATE DATETIME = '2023-07-03 08:00:00'; -- START DATE RANGE@ENDDATE
DECLARE @ENDDATE DATETIME = '2023-07-03 23:59:59'; -- END DATE RANGE
DECLARE @PLOGID INT = 14634428;

--SELECT * 
--FROM SH_BATCH_LOG 
--WHERE CREATE_DATE BETWEEN @STARTDATE AND @ENDDATE
--AND GROUP_NAME LIKE '%GL EXPORT%'
--AND TOTAL_RECORDS IS NOT NULL;

-- List processed batches by workers
-- Column with NOT NULL TOTAL_RECORDS are batches processed (batch per worker are set to 400 entries)

-- Count totals succeeded and failed trns
SELECT SUM(TOTAL_FAILED) AS Count_Total_Failed, SUM(TOTAL_SUCCESS) as Count_Successed 
FROM SH_BATCH_LOG 
WHERE CREATE_DATE BETWEEN @STARTDATE AND @ENDDATE
AND GROUP_NAME LIKE '%GL EXPORT%'
AND TOTAL_RECORDS IS NOT NULL
--AND PARENT_LOG_ID=@PLOGID;

-- Count total transactions processed
SELECT COUNT(ID) AS Count_processed_batches 
FROM SH_BATCH_LOG 
WHERE CREATE_DATE BETWEEN @STARTDATE AND @ENDDATE
AND GROUP_NAME LIKE '%GL EXPORT%'
AND TOTAL_RECORDS IS NOT NULL
--AND PARENT_LOG_ID=@PLOGID;

SELECT CREATE_DATE, UPDATE_STATUS_DATE, TRANSFER_TYPE, STATUS, TOTAL_RECORDS, TOTAL_SUCCESS, TOTAL_FAILED 
FROM SH_BATCH_LOG 
WHERE CREATE_DATE BETWEEN @STARTDATE AND @ENDDATE
AND GROUP_NAME LIKE '%GL EXPORT%'
AND TOTAL_RECORDS IS NOT NULL
--AND PARENT_LOG_ID=@PLOGID
ORDER BY UPDATE_STATUS_DATE DESC;

-- List waiting batches to process (future GL Exporter worker batches)
-- List total transactions wating
SELECT COUNT(ID) AS Count_togo_batches
FROM SH_BATCH_LOG 
WHERE CREATE_DATE BETWEEN @STARTDATE AND @ENDDATE
AND GROUP_NAME LIKE '%GL EXPORT%'
AND TOTAL_RECORDS IS NULL;
--AND PARENT_LOG_ID=@PLOGID;

-- List transactions detail
SELECT * 
FROM SH_BATCH_LOG 
WHERE CREATE_DATE BETWEEN @STARTDATE AND @ENDDATE
AND GROUP_NAME LIKE '%GL EXPORT%'
AND TOTAL_RECORDS IS NULL
--AND PARENT_LOG_ID=@PLOGID
ORDER BY UPDATE_STATUS_DATE DESC;

-- Kill process
--SELECT * FROM SH_BATCH_LOG WHERE ID=14613072;
--UPDATE SH_BATCH_LOG SET STATUS = 6 WHERE ID =14613072;
-- SELECT * FROM SH_BATCH_LOG WHERE ID=14607504;