-- IDIT_LIST_ Exported transactions to SAP.sql
-- List GL Transactions marked as exported to MOEX/SAP 
-- Provide start date and end date before run query.
-- Warning : This query searches on AC_GL_INTERFACE (biggest table in IDIT)
-- Please filter wisely on dates...

DECLARE @STARTDATE DATETIME = '2023-10-02 12:00:00'; -- START DATE RANGE
DECLARE @ENDDATE DATETIME = '2023-10-04 20:0:00'; -- END DATE RANGE

SELECT DISTINCT AC_TRANSACTION.ID,
                T_TRANSACTION_TYPE.DESCRIPTION,
                AC_GL_INTERFACE.INSERT_DATE,
                AC_GL_INTERFACE.TRANSFER_DATE
FROM AC_GL_INTERFACE WITH (nolock)
INNER JOIN AC_ENTRY ON AC_GL_INTERFACE.ENTRY_ID = AC_ENTRY.id
INNER JOIN AC_TRANSACTION ON AC_ENTRY.TRANSACTION_ID = AC_TRANSACTION.ID
INNER JOIN T_TRANSACTION_TYPE ON AC_GL_INTERFACE.TRANSACTION_TYPE = T_TRANSACTION_TYPE.id
WHERE 
    AC_GL_INTERFACE.INSERT_DATE  BETWEEN @STARTDATE AND @ENDDATE 
	AND AC_GL_INTERFACE.TRANSACTION_TYPE not in(10077,1000001)   
ORDER BY AC_GL_INTERFACE.INSERT_DATE DESC;
